### PR TITLE
Add Littlefuse LVR100-200 Series

### PR DESCRIPTION
**Pull request by svheymann**

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you post a screenshot and give a list of changes?
Also post a link to the datasheet you used to design this footprints.

**Comment by svheymann** [comment]
http://www.littelfuse.com/~/media/electronics/datasheets/resettable_ptcs/littelfuse_ptc_lvr_catalog_datasheet.pdf.pdf

grafik

**Comment by svheymann** [comment]
Added Littelfuse LVR100
Added Littelfuse LVR125
Added Littelfuse LVR200

**Comment by poeschlr** [comment]
Sorry for the long wait. I had quite a bit to do this month.

The footprints looks nice over all. But there are a few [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) violations.

1. Fill out the 3d shapes path even if you do not provide a 3d model yourself. (This way a user can simply add a 3d model to the correct directory.) Rule 10.4
2. Courtyard clearance is 0.25mm as measured from the body of the part. It should be the same all around the part. Rule 7.5.iv 
  - LVR100 currently has a clearance of 0.3mm. But on the right side you have 0.29mm
  - LVR125 has a clearance of 0.3mm in y direction, 0.26mm on the left side and 0.24mm on the right side
  - LVR200 has 0.3mm in y direction, 0.31mm on the left and 0.29mm on the right side.
3. I think it would look better if the reference on f.fab layer is on y=0
4. The clearance between part body and silk layer does not need to be this large.

I would accept your footprint without fixing my points 3 and 4. (These are my opinions and not really part of the library rules.)

**Comment by evanshultz** [comment]
@svheymann Will you be able to make the changes requested above?

**Comment by svheymann** [comment]
done.

**Comment by poeschlr** [comment]
Would it be possible for you to add ${KISYS3DMOD}/ to the 3d model path? 
Should have the form: ${KISYS3DMOD}/footprint_lib_name.3dshapes/footprint_name.wrl
Other than that these footprints are ready to be merged.

**Comment by svheymann** [comment]
done.

**Comment by poeschlr** [comment]
It seems there was a misunderstanding. (The lib name is still needed.)
The full 3d paths should be 
- for LVR100: ${KISYS3DMOD}/Fuse_Holders_and_Fuses.3dshapes/Fuse_Littelfuse-LVR100.wrl
- for LVR125: ${KISYS3DMOD}/Fuse_Holders_and_Fuses.3dshapes/Fuse_Littelfuse-LVR125.wrl
- for LVR200: ${KISYS3DMOD}/Fuse_Holders_and_Fuses.3dshapes/Fuse_Littelfuse-LVR200.wrll

**Comment by poeschlr** [comment]
@svheymann could you find the time to make these last simple changes?

**Comment by poeschlr** [comment]
This can be closed as soon as #16 is merged.

**Pull request closed without merging**
