### PR TITLE
Added two new fuses

### PR DESCRIPTION
**Pull request by SchrodingersGat**
* FuseHolder_Keystone_MINI_3568
* FuseHolder_LittleFuse_Nano-157

Added Fab layer to Fuse_SMD2920

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
This is a fix for the issues in https://github.com/KiCad/Fuse_Holders_and_Fuses.pretty/pull/4

**Comment by jkriege2** [comment]
Hi!

nice work ... maybe two minor changes:
2017-01-08 20_01_49-footprint editor no active library
2017-01-08 20_02_52-footprint editor no active library

**Comment by jkriege2** [comment]
Oh and in `Fuse_SMD2920` the F.Fab-width is 0.15 ... please fix!

**Comment by SchrodingersGat** [comment]
Ok @jkriege2 ready to check again :)

**Comment by jkriege2** [comment]
Hi!

- `Fuse_SMD2920`: OK!
- `FuseHolder_LittleFuse_Nano-157`: F.Fab/F.SilkS have the wrong widths
- `FuseHolder_Keystone_MINI_3568`: F.Fab/F.SilkS have the wrong widths
- `FuseHolder_Keystone_MINI_3557-2`:  F.CrtYd/F.SilkS have the wrong widths, no F.Fab-outline

Please fix?

Best,
JAN

**Comment by jkriege2** [comment]
PS: Please also compare with https://github.com/KiCad/Fuse_Holders_and_Fuses.pretty/pull/9 ... as I also fixed the `Fuse_SMD2920`  + all other fuses!

**Comment by evanshultz** [comment]
@SchrodingersGat Does Jan's comment above mean this PR can be closed? At any rate the branch is now outdated and possibly ugly to fix up and merge.

**Comment by SchrodingersGat** [comment]
I'll close this one for now

**Pull request closed without merging**
