### PR TITLE
added Fuse_SMD_Schurter_OMT125.kicad_mod

### PR DESCRIPTION
**Pull request by feichtinger**
bildschirmfoto vom 2016-10-24 21-47-48

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

First of all output of KLC-check:
```
checking module: Fuse_SMD_Schurter_OMT125
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.15mm line width and provides a reference mark for pin 1. (IPC-7351).
```

Other comments:
1. Silkscreen should not be below SMD components, see e.g.:
2016-10-25 07_37_14-footprinteditor keine aktive bibliothek
2. For KLC 10.4 `Fuse_SMD_SCHURTER_OMT125` -> `Fuse_SMD_Schurter_OMT125` (casing of manufacturer name is different!)

Best and thanks,
JAN

**Comment by feichtinger** [comment]
OK.

**Comment by jkriege2** [comment]
Hi!

better, but the CourtYard should be 0.25mm offset AROUND the SilkScreen (except the REF-text!). Compare Fuse_SMD2920 above ...

Could you still change that?

Best,
JAN

**Comment by feichtinger** [comment]
> but the CourtYard should be 0.25mm offset AROUND the SilkScreen

Well, the KLC 6.6 defines the courtyard around the pads and the body, and not the silkscreen:
> Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.

But I will change it anyway.

**Comment by jkriege2** [comment]
Hi!

that's how I understood the KLC (and how my footprints were critisized ;-), but since I'm relatively new as a lib maintainer, I'll ask around ;-) ... I'll let you know.

Best,
JAN

**Comment by jkriege2** [comment]
OK, thanks!
JAN

**Pull request merged**
