### PR TITLE
Fixed naming for Schurter FUP footprint

### PR DESCRIPTION
**Pull request by poeschlr**
I had a typo in the company name (Schruter instead of Schurter)
I now use the new naming scheme.

This footprint is valid for two different parts. One part is valid for a 5x20mm fuse the other for the 6.3x32mm fuse. This makes the naming and description quite hard to understand. (Should we duplicate it for each fuse type?)

3d part renaming pull requests:
kicad-library repo: https://github.com/KiCad/kicad-library/pull/1760
packages3d repo: https://github.com/KiCad/kicad-packages3D/pull/149
packages3d-source repo: https://github.com/KiCad/kicad-packages3D-source/pull/59

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please duplicate for each fuse type

**Comment by poeschlr** [comment]
There are now two footprints (one for each fuse type)
They share the 3d model. (From the outside the fuse holders look the same.)

**Comment by poeschlr** [comment]
Fixed 3d path. Why did travis not catch that the lib name was missing from the path?

**Comment by SchrodingersGat** [comment]
Cool, there was a KLC script error previously. Happy to merge now. Thanks

**Pull request merged**
