### PR TITLE
Fuse additions

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added Keystone 3568 holder
Added Fab outline to SMD2920

### CODE REVIEW

**Comment by jkriege2** [comment]
Please fix:
```
checking module: FuseHolder_Keystone_MINI_3568
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
```

... and is there a special reason why you have the name in the above-mentioned footprint?
The other footprints are OK.

cu
JAN

**Comment by SchrodingersGat** [comment]
Hmm as this one has two pin 1 numbers, I don't think this will ever pass that check.

The other THT fuse holders do not conform to this rule either, I think is is probably ok?

**Comment by jkriege2** [comment]
Maybe move origin to ONE of the 1-pins? ... THe other THTs are also done in a way that origin is on a one pin ...

JAN

**Comment by SchrodingersGat** [comment]
Fair enough, done :)

**Comment by jkriege2** [comment]
Hi!

I think the relevant (remaining) errors are:
- `FuseHolder_Keystone_MINI_3568`: CrtYrd is not on a 0.05" grid ... + Fab should be 0.10mm thick ... 
- `FuseHolder_LittleFuse_Nano-157`: Fab should be 0.10mm thick ... 
- `Fuse_SMD2920`: Fab should be 0.10mm thick ... 

When that's fixed, I think we can merge ...

JAN

**Pull request closed without merging**
