### PR TITLE
Added Footprint for Fuse-Holder from Schurter

### PR DESCRIPTION
**Pull request by McSpeck**
Added this Footprint. I already used it in an pcb. So it works. 
Please check if its ok.

Regards from Germany
McSpeck

### CODE REVIEW

**Comment by pointhi** [comment]
Please appy KLC:

```
checking module: Fuseholder_5x20_Horizon_Open_Schurter_0031_8201
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
```

Furthermore in my opinion, I think the silkscreen on the mechanical hole can be removed.
The same with the german keyword ```Sicherungshalter```

Datasheet: http://www.schurter.com/var/schurter/storage/ilcatalogue/files/document/datasheet/en/pdf/typ_OGN.pdf

**Comment by McSpeck** [comment]
Hi pointhi,
i corrected the issues you mentioned above. Should be ok now.

regards....

**Comment by pointhi** [comment]
Hy,

* I would propose you to change the footprint name to something like ```Fuseholder5x20_horiz_open_Schurter_0031_8201.kicad_mod``` to have a more similar naming scheme.
* Also, I don't know why you marked pin 1 (fuses have no direction, and the component also seems not to have a desired installation direction)
* There is a unwritten "rule" where the reference text is normaly places on top of the footprint, and value on the bottom
* description is missing a ```f``` at the beginning. Probably repleacing it with the footprint datasheet url (which would be more informative, and not a redundant text as now)
* the silkscreen is a little bit to long for this component (from the look at the datasheet). I would propose you to create a silkscreen, which is about the size of the real component (even the silkscreen get seperated between the pins. Look for example onto ```Fuseholder6x32_Horiz_Open_Schurter0031-8002``` how this could be done. Please also adjust the courtjard after redrawing the silk screen.

After fixing this, It should fit all requirements.

**Comment by McSpeck** [comment]
Hi pointhi ,

I gave my best :D

regards...

**Comment by pointhi** [comment]
Hy McSpeck,

The footprint looks good to  me.

The last thing I'm not sure is KLC rule 6.5:
```Silkscreen is not superposed to pads, its outline is completely visible after board assembly```

I have only the datasheet, so I cannot remeassure the outline of this component. But when I compare it with the image of the datasheet, the outline between the pads is drawn too far inside (from what I see). It's not a problem to have a silkscreen with holes in the outline.

**Comment by McSpeck** [comment]
I have some laying around here. What i have measured it seems to be 1,5 to 2.5mm the plastic case spares out around the pins.
But if you want to i can still draw a less complicated outline for it.

**Comment by pointhi** [comment]
complicated silkscreens are not a problem. But the outline of the silkscreen normaly represent the outline of the component as good as possible. In my opinion, a correct outline with a gap in it is preverable to something continuously but which does not represent the real outline of the component.

**Comment by McSpeck** [comment]
hi pointhi,

changed.

**Comment by pointhi** [comment]
Thanks for your contribution

**Pull request merged**
